D8MT-2399: Code upgraded to provide compatibility with Drupal 9.
openeuropa/oe_migration pull request #11
Opened 2021-12-15 12:52 UTC by emhernapa

## OPENEUROPA-D8MT-2399

### Description

Based on the results performed in the analysis for the Drupal 9 code compatibility, perform the necessary code refactoring in order to ensure that "oe_migration" code is compatible with Drupal 9.

### Change log

- Changed: Provided code compatibility with Drupal 9.

2022-01-12 13:49 UTC, MiguelArber approved these changes, later dismissed
Drupal 9 compatibility changes seem to be correct.

2022-01-14 15:19 UTC, upchuk requested changes

2022-01-14 15:19 UTC, upchuk commented on modules/oe_migration_workflow/tests/src/Unit/Plugin/migrate/process/SetWorkflowStateTest.php
> -  public function testInvalidWorkflowName() {
Why was this test removed?

2022-01-17 08:35 UTC, MiguelArber commented on modules/oe_migration_workflow/tests/src/Unit/Plugin/migrate/process/SetWorkflowStateTest.php
> -  public function testInvalidWorkflowName() {
Hi @upchuk, thanks for noticing. It was removed temporarily and I didn’t restore it. I will put it back again, thanks.

2022-01-17 11:07 UTC, MiguelArber commented on modules/oe_migration_workflow/tests/src/Unit/Plugin/migrate/process/SetWorkflowStateTest.php
> -  public function testInvalidWorkflowName() {
Missing test was restored.

2022-01-17 11:08 UTC, MiguelArber commented on modules/oe_migration_workflow/tests/src/Unit/Plugin/migrate/process/SetWorkflowStateTest.php
> +  /**
@upchuk Test was restored. Thank you.
Cc.: @ioannis-ampatzis

2022-01-17 11:10 UTC, MiguelArber commented on modules/oe_migration_workflow/tests/src/Unit/Plugin/migrate/process/SetWorkflowStateTest.php
> +
@upchuk Missing test was restored. Thanks for your feedback.
Cc.: @ioannis-ampatzis

2022-01-17 11:18 UTC, ioannis-ampatzis approved these changes
After the restoration of the deleted test, everything works as expected.

2022-01-17 13:04 UTC, upchuk approved these changes

2022-01-17 13:17 UTC, merged